name: Build and Push Multi-Arch Container Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
  # Run every 14 days at 00:00 UTC
  schedule:
    - cron: "0 0 */14 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Install QEMU static binaries for multi-architecture support
      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Log in to Docker Hub or other container registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and push the multi-architecture Docker image
      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/blogbench:1.2
